#include "sidecar/database/database.hpp"
#include "sidecar/storage/physics.hpp"

#include <sqlite3.h>

#include <algorithm>
#include <cmath>
#include <filesystem>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {
using namespace sidecar::storage;

void Expect(bool condition, const std::string& message) {
    if (!condition) throw std::runtime_error(message);
}

StorageTarget Target() {
    StorageTarget value;
    value.machine_hash = std::string(64, 'a');
    value.persistent_id = "synthetic-nvme";
    value.model = "Synthetic NVMe";
    value.bus_type = "NVMe";
    value.physical_disk_number = 7;
    value.volume_name = "synthetic-volume";
    value.mount_point = "X:\\";
    value.dataset_path = "X:\\SidecarData\\dataset.bin";
    value.alignment = {512, 4096, 512, 4096, "synthetic"};
    return value;
}

void TestDatasetGenerator() {
    std::vector<std::byte> a(65539), b(65539);
    FillDatasetBytes(a.data(), 3, a.size());
    FillDatasetBytes(b.data(), 3, b.size());
    Expect(a == b, "dataset generator is not deterministic");
    Expect(VerifyDatasetBytes(a.data(), 3, a.size()), "generated bytes do not verify");
    a[500] ^= std::byte{1};
    Expect(!VerifyDatasetBytes(a.data(), 3, a.size()), "corruption was not detected");
    Expect(DatasetIdentityHash(kDefaultDatasetBytes) ==
           DatasetIdentityHash(kDefaultDatasetBytes), "dataset identity is unstable");
    Expect(DatasetIdentityHash(kDefaultDatasetBytes) !=
           DatasetIdentityHash(kDefaultDatasetBytes / 2), "dataset size missing from identity");
}

void TestOffsetGeneration() {
    BenchmarkConfig config;
    config.block_bytes = 65536;
    config.request_count = 1024;
    config.pattern = AccessPattern::Pseudorandom;
    const auto a = GenerateOffsets(config, 1ULL << 30U);
    const auto b = GenerateOffsets(config, 1ULL << 30U);
    Expect(a == b && a.size() == config.request_count, "random offsets are unstable");
    Expect(std::all_of(a.begin(), a.end(), [&](auto offset) {
        return offset % config.block_bytes == 0 &&
               offset + config.block_bytes <= (1ULL << 30U);
    }), "random offsets violate dataset/alignment bounds");
    Expect(std::vector<std::uint64_t>(a.begin(), a.begin() + 64) !=
           std::vector<std::uint64_t>(b.rbegin(), b.rbegin() + 64),
           "pseudorandom ordering degenerated");
    config.pattern = AccessPattern::Sequential;
    const auto sequential = GenerateOffsets(config, 4 * config.block_bytes);
    Expect(sequential[0] == 0 && sequential[1] == config.block_bytes &&
           sequential[4] == 0, "sequential wrap ordering is wrong");
    config.pattern = AccessPattern::Windowed;
    config.window_bytes = 16 * config.block_bytes;
    const auto windowed = GenerateOffsets(config, 1ULL << 30U);
    const auto minimum = *std::min_element(windowed.begin(), windowed.end());
    const auto maximum = *std::max_element(windowed.begin(), windowed.end());
    Expect(maximum - minimum < config.window_bytes, "windowed pattern escaped its window");
}

void TestValidationAndPlan() {
    auto target = Target();
    BenchmarkConfig config;
    config.block_bytes = 1000;
    Expect(ValidateConfig(config, target, kDefaultDatasetBytes).has_value(),
           "misaligned unbuffered block accepted");
    config.block_bytes = 4096;
    config.queue_depth = 64;
    config.outstanding_byte_cap = 4096;
    Expect(ValidateConfig(config, target, kDefaultDatasetBytes).has_value(),
           "outstanding-byte cap ignored");
    config.backend = BackendKind::MemoryMapped;
    config.queue_depth = 2;
    config.outstanding_byte_cap = 1ULL << 30U;
    Expect(ValidateConfig(config, target, kDefaultDatasetBytes).has_value(),
           "mapped QD greater than one accepted");

    DatasetIdentity dataset;
    dataset.path = target.dataset_path;
    dataset.size_bytes = kDefaultDatasetBytes;
    dataset.identity_hash = DatasetIdentityHash(dataset.size_bytes);
    const auto plan = BuildDefaultPlan(target, dataset, 96ULL << 30U);
    Expect(plan.entries.size() == 187, "default matrix configuration count changed");
    auto contains = [&](std::uint64_t block, std::uint32_t qd) {
        return std::any_of(plan.entries.begin(), plan.entries.end(), [&](const auto& entry) {
            return entry.config.backend == BackendKind::OverlappedUnbuffered &&
                   entry.config.pattern == AccessPattern::Sequential &&
                   entry.config.destination == DestinationKind::PageablePretouched &&
                   entry.config.block_bytes == block && entry.config.queue_depth == qd;
        });
    };
    Expect(contains(128ULL << 20U, 2) && contains(64ULL << 20U, 4) &&
           contains(32ULL << 20U, 8) && contains(16ULL << 20U, 16),
           "256 MiB aggregate submission shapes are missing");
    const auto direct_count = std::count_if(plan.entries.begin(), plan.entries.end(),
        [](const auto& entry) {
            return entry.config.backend == BackendKind::DirectStorage &&
                   entry.disposition == RunStatus::SkippedUnsupported;
        });
    Expect(direct_count == 2, "DirectStorage controls are not explicitly skipped");
}

void TestStatisticsAndDeadlines() {
    std::vector<double> small{1, 2, 3, 4, 5};
    const auto summary = Summarize(small);
    Expect(summary.count == 5 && summary.p50 == 3 && !summary.p999,
           "small distribution percentile semantics are wrong");
    std::vector<double> large(1000);
    for (std::size_t index = 0; index < large.size(); ++index)
        large[index] = static_cast<double>(index);
    Expect(Summarize(large).p999.has_value(), "P99.9 not reported with adequate samples");
    std::vector<RequestSample> samples(4);
    for (std::size_t index = 0; index < samples.size(); ++index) {
        samples[index].status = RunStatus::Success;
        samples[index].completion_latency_ns = (index + 1) * 1000000ULL;
        samples[index].completed_bytes = 4096;
    }
    const auto deadlines = EvaluateDeadlines(samples, 10000000);
    Expect(deadlines[1].deadline_ns == 1000000 && deadlines[1].hits == 1 &&
           deadlines[1].misses == 3, "deadline hit/miss accounting is wrong");
}

void TestFinalizationAndJson() {
    BenchmarkResult value;
    value.config.request_count = 2;
    value.wall_time_ns = 1000000000;
    value.samples.resize(2);
    for (auto& sample : value.samples) {
        sample.status = RunStatus::Success;
        sample.requested_bytes = sample.completed_bytes = 1024;
        sample.completion_latency_ns = 1000;
    }
    FinalizeBenchmark(value);
    Expect(value.completed_bytes == 2048 && value.bytes_per_second == 2048 &&
           std::abs(value.iops - 2.0) < .001, "benchmark finalization is wrong");
    Expect(ResultToJson(value) == ResultToJson(value), "result JSON is unstable");
    HealthSnapshot health;
    const auto json = HealthToJson(health);
    Expect(json.find("\"temperature_c\":null") != std::string::npos,
           "unsupported health fields are not explicit nulls");
}

class SyntheticProvider final : public IStorageProvider {
public:
    StorageTarget ResolveTarget(const std::optional<std::string>&,
                                const std::optional<std::filesystem::path>&) override {
        return Target();
    }
    DatasetIdentity InspectDataset(const StorageTarget& target) override {
        DatasetIdentity value; value.path=target.dataset_path; value.exists=true;
        value.verified=true; value.identity_hash=DatasetIdentityHash(value.size_bytes);
        return value;
    }
    DatasetIdentity CreateDataset(const StorageTarget& target, std::uint64_t) override {
        return InspectDataset(target);
    }
    DatasetIdentity VerifyDataset(const StorageTarget& target, bool) override {
        return InspectDataset(target);
    }
    HealthSnapshot CaptureHealth(const StorageTarget&, std::string phase) override {
        HealthSnapshot value; value.phase=std::move(phase); value.status="SUCCESS";
        value.temperature_c=40; return value;
    }
    BenchmarkResult Run(const StorageTarget&, const BenchmarkConfig& config) override {
        BenchmarkResult value; value.config=config; value.status=RunStatus::Success;
        return value;
    }
    bool DirectStorageAvailable() const noexcept override { return false; }
};

void TestProviderInjection() {
    SyntheticProvider provider;
    auto target=provider.ResolveTarget(std::nullopt,std::nullopt);
    Expect(target.model=="Synthetic NVMe", "injected provider target was not used");
    Expect(provider.VerifyDataset(target,false).verified,
           "injected provider dataset verification failed");
    Expect(provider.CaptureHealth(target,"TEST").temperature_c==40,
           "injected health source was not used");
}

void TestMigrationAndPersistence() {
    const auto path = std::filesystem::temp_directory_path() / "sidecar-storage-wu7-test.db";
    std::error_code ignored;
    std::filesystem::remove(path, ignored);
    auto database = sidecar::database::Database::Open(
        path, sidecar::database::OpenMode::CreateOrOpen);
    database.Initialize();
    Expect(database.Status().schema_version == sidecar::database::kCurrentSchemaVersion,
           "migration 007 was not applied");
    sidecar::database::HardwareProfileInput profile;
    profile.machine_hash = std::string(64, 'a');
    profile.discovery_json = "{}";
    sidecar::database::StorageDeviceInput storage;
    storage.persistent_id = "synthetic-nvme";
    storage.model = "Synthetic NVMe";
    storage.bus_type = "NVMe";
    storage.topology_json = "{}";
    storage.volumes_json = "[]";
    storage.topology_confidence = "DIRECTLY_REPORTED";
    database.RefreshHardwareInventory(profile, {}, {storage}, false, true);
    const auto session = database.StartBenchmarkSession(
        {profile.machine_hash, "M0-FROZEN-1", std::string(40, '1'), std::nullopt,
         "STORAGE_PHYSICS_WU7", std::nullopt});
    sidecar::database::StorageDatasetInput dataset{
        profile.machine_hash, storage.persistent_id, "generator", std::string(64, 'd'),
        "X:/dataset.bin", "volume", 1, 7, 8192, 7, true, false, 4096};
    dataset.full_verification = true;
    dataset.verified_bytes = 8192;
    const auto first = database.UpsertStorageDataset(dataset);
    dataset.full_verification = false;
    dataset.verified_bytes = 4096;
    const auto second = database.UpsertStorageDataset(dataset);
    Expect(first == second, "dataset upsert created a duplicate");
    sqlite3* audit = nullptr;
    Expect(sqlite3_open(path.generic_string().c_str(), &audit) == SQLITE_OK,
           "could not open dataset evidence audit connection");
    sqlite3_stmt* evidence = nullptr;
    Expect(sqlite3_prepare_v2(audit,
        "SELECT full_verification,verified_bytes FROM storage_datasets WHERE storage_dataset_id=1",
        -1, &evidence, nullptr) == SQLITE_OK && sqlite3_step(evidence) == SQLITE_ROW,
        "could not query dataset verification evidence");
    Expect(sqlite3_column_int(evidence, 0) == 1 &&
           sqlite3_column_int64(evidence, 1) == 8192,
           "sampled verification downgraded full verification evidence");
    sqlite3_finalize(evidence);
    sqlite3_close(audit);
    sidecar::database::StorageHealthSnapshotInput health;
    health.machine_hash=profile.machine_hash; health.persistent_id=storage.persistent_id;
    health.session_id=session; health.phase="BEFORE"; health.provider="SYNTHETIC";
    health.status="SUCCESS"; health.raw_evidence_json="{}";
    const auto health_id=database.InsertStorageHealthSnapshot(health);
    sidecar::database::StorageConfigurationInput config;
    config.session_id=session; config.storage_dataset_id=first;
    config.configuration_hash=std::string(64,'c'); config.backend="UNBUFFERED";
    config.access_pattern="SEQUENTIAL"; config.destination_kind="PAGEABLE";
    config.block_bytes=4096; config.queue_depth=1; config.request_count=1;
    config.outstanding_byte_cap=4096; config.timeout_ms=1000; config.phase="TEST";
    config.cache_classification="CACHE_BYPASSED"; config.status="SUCCESS";
    const auto config_id=database.InsertStorageConfiguration(config);
    sidecar::database::StorageBenchmarkInput benchmark;
    benchmark.configuration_id=config_id; benchmark.health_before_id=health_id;
    benchmark.status="SUCCESS"; benchmark.statistics_json=
        "{\"completion_latency_ns\":{\"count\":1,\"p50\":1,\"p95\":1,\"p99\":1}}";
    benchmark.cpu_json="{}"; benchmark.verified=true; benchmark.completed_bytes=4096;
    benchmark.wall_time_ns=1000; benchmark.bytes_per_second=4096e6; benchmark.iops=1e6;
    const auto benchmark_id=database.InsertStorageBenchmark(benchmark);
    database.InsertStorageSample({benchmark_id,0,0,0,4096,4096,0,1,2,1,"SUCCESS",std::nullopt});
    database.InsertStorageDeadline({benchmark_id,1000000,1,0,1.0,4096e6});
    database.InsertStorageBackendProfile(
        {session,"UNBUFFERED","SEQUENTIAL","PAGEABLE",4096e6,4096,1});
    database.CompleteBenchmarkSession(session, "COMPLETE");
    const auto counts=database.StorageCounts();
    Expect(counts.datasets==1 && counts.health_snapshots==1 && counts.configurations==1 &&
           counts.benchmarks==1 && counts.samples==1 && counts.deadline_profiles==1 &&
           counts.backend_profiles==1, "storage persistence counts are wrong");
    Expect(database.LatestStorageBenchmarks().size()==1, "storage report query failed");
    const auto status = database.Status();
    Expect(status.foreign_key_violations == 0, "storage persistence has FK violations");
}

}  // namespace

int main() {
    const std::vector<std::pair<const char*, void(*)()>> tests{
        {"dataset_generator", TestDatasetGenerator},
        {"offset_generation", TestOffsetGeneration},
        {"validation_and_plan", TestValidationAndPlan},
        {"statistics_and_deadlines", TestStatisticsAndDeadlines},
        {"finalization_and_json", TestFinalizationAndJson},
        {"provider_injection", TestProviderInjection},
        {"migration_and_persistence", TestMigrationAndPersistence},
    };
    std::size_t passed = 0;
    for (const auto& [name, test] : tests) {
        try { test(); ++passed; std::cout << "PASS " << name << '\n'; }
        catch (const std::exception& error) {
            std::cerr << "FAIL " << name << ": " << error.what() << '\n';
        }
    }
    std::cout << passed << '/' << tests.size() << " storage tests passed\n";
    return passed == tests.size() ? 0 : 1;
}
